# Generated by Django 3.1.2 on 2021-01-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
