# Generated by Django 3.1.2 on 2020-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0003_auto_20201030_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='communities',
            field=models.ManyToManyField(to='community.community'),
        ),
    ]
