# Generated by Django 3.1.2 on 2020-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_communities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='communities',
        ),
    ]
