# Generated by Django 3.1.2 on 2021-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_communities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='profile_p', to='users.Media'),
        ),
    ]
