# Generated by Django 3.1.2 on 2020-11-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community_name',
            field=models.CharField(max_length=100),
        ),
    ]
