# Generated by Django 3.1.2 on 2020-11-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20201116_1128'),
        ('post', '0002_auto_20201124_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
    ]
