# Generated by Django 3.1.2 on 2020-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201124_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community_name',
        ),
        migrations.AddField(
            model_name='post',
            name='communityID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
