# Generated by Django 3.1.2 on 2020-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201124_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='communityID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
