# Generated by Django 3.1.2 on 2020-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201126_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='reporting_reason',
            field=models.CharField(choices=[('Annoying content', 'Annoying content'), ('Spam', 'Spam'), ('Inappropriate content', 'Inappropriate content'), ('This profile is pretending to be someone else', 'This profile is pretending to be someone else'), ('Other things that are not mentioned above', 'Other things that are not mentioned above')], default=None, max_length=50, null=True),
        ),
    ]
