# Generated by Django 3.1.2 on 2020-11-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201126_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='reporting_reason',
        ),
    ]
