# Generated by Django 3.1.2 on 2020-11-30 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_auto_20201126_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('postID', models.IntegerField(null=True)),
                ('post_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='post.communitypost')),
                ('users_liked', models.ManyToManyField(default=None, related_name='like_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
