# Generated by Django 3.1.2 on 2020-12-01 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
