# Generated by Django 3.1.2 on 2020-12-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_communitypost_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_name',
        ),
    ]
