# Generated by Django 3.1.2 on 2020-12-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_communitypost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypost',
            old_name='video',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='photo',
        ),
    ]
