# Generated by Django 3.1.2 on 2020-12-03 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0016_auto_20201203_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypost',
            old_name='file',
            new_name='myFile',
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='users_liked',
            field=models.ManyToManyField(default=None, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='users_reported',
            field=models.ManyToManyField(default=None, related_name='users_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
