# Generated by Django 3.1.2 on 2020-12-10 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0019_auto_20201210_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='postlike',
            name='liked_by',
            field=models.ManyToManyField(default=None, null=True, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
