# Generated by Django 3.1.2 on 2020-12-10 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0020_auto_20201210_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_by',
            field=models.ManyToManyField(default=None, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
