# Generated by Django 3.1.2 on 2020-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='community',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
