# Generated by Django 3.1.2 on 2020-11-12 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='username',
            new_name='communityID',
        ),
        migrations.AddField(
            model_name='community',
            name='field',
            field=models.CharField(choices=[('actor', 'actor'), ('anime', 'anime'), ('art', 'art'), ('astronomy', 'astronomy'), ('beauty', 'beauty'), ('book', 'book'), ('celebrities', 'celebrities'), ('comic', 'comic'), ('cooking', 'cooking'), ('game', 'game'), ('history', 'history'), ('medicine', 'medicine'), ('movie', 'movie'), ('music', 'music'), ('painting', 'painting'), ('sport', 'sport'), ('others', 'others')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
