# Generated by Django 3.1.2 on 2020-12-16 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_auto_20201116_1128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('photo', models.ImageField(null=True, upload_to='events/')),
                ('creator', models.CharField(blank=True, max_length=150)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_community', to='community.community')),
                ('join_users', models.ManyToManyField(default=None, related_name='users_join', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
